apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: omphalos
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - configmap.yaml
  - pvc.yaml
  - cronjob.yaml
