apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: omphalos
  namespace: omphalos
subjects:
  - kind: ServiceAccount
    name: omphalos
    namespace: omphalos
roleRef:
  kind: Role
  name: omphalos
  apiGroup: rbac.authorization.k8s.io
